### PR TITLE
Helper functions for text color and typing speed

### LINKED ISSUE #3: Create Adventure 2
Create an adventure for our protag to go on!

### PR DESCRIPTION
**Pull request by sselin-co**
This pull request contains helper functions I wrote that can be used to add text color in the console as well as control the speed of typing for dramatic effect.

### CODE REVIEW

**Review by shepkeira — DISMISSED** [review]

**Comment by Rock-it-science** [comment]
I like it. This is probably the best way to do it.

**Review by Rock-it-science — DISMISSED** [review]

**Comment by Rock-it-science** [comment]
Should adventure B in a different branch?

**Comment by sselin-co** [comment]
I assumed any work related to my assigned issue (issue 2) would be done on this branch. Though I can definitely make a new branch for the adventure if that makes more sense.

**Comment by Rock-it-science** [comment]
Actually that should be totally fine, it probably doesn't make much difference if the changes are coming from this branch or a separate one, especially for the purpose of this assignment.

**Review by Rock-it-science — APPROVED** [review]

**Pull request merged**
